version: "3"

services:
  document-editor-app:
    container_name: document-editor-app
    build: .
    ports:
      - 1337:1337
  database:
    image: mongo
    container_name: document-editor-app-db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=document-editor
    ports:
      - 27017-27019:27017-27019
    volumes:
      - db-data:/data/db
volumes:
  db-data:
    driver: local
