// split to send\received events
export enum DOCUMENT_EVENTS {
  OPEN = "OPEN",
  CLOSE = "CLOSE",
  NEW_WATCHER = "NEW_WATCHER",
  WATCHER_LEAVE = "WATCHER_LEAVE",
  DOCUMENT_BODY_UPDATE = "DOCUMENT_BODY_UPDATE",
  DELETE = "DELETE",
  NEW_DOCUMENT = "NEW_DOCUMENT",
  DOCUMENT_UPDATE = "DOCUMENT_UPDATE",
}
