// split to send\received events
export enum DOCUMENT_EVENTS {
  OPEN = "OPEN",
  CLOSE = "CLOSE",
  NEW_WATCHER = "NEW_WATCHER",
  WATCHER_LEAVE = "WATCHER_LEAVE",
  DOCUMENT_UPDATE = "DOCUMENT_UPDATE",
}
